all:
	latex barbican.tex
	latex ceilometer.tex
	latex cinder.tex
	latex clients.tex
	latex commonlibraries.tex
	latex deployment.tex
	latex designate.tex
	latex documentation.tex
	latex glance.tex
	latex heat.tex
	latex horizon.tex
	latex  infrastructure.tex
	latex ironic.tex
	latex keystone.tex
	latex manila.tex
	latex neutron.tex
	latex nova.tex
	latex others.tex
	latex qualityassurance.tex
	latex releasecyclemanagement.tex
	latex sahara.tex
	latex swift.tex
	latex trove.tex
	latex zaqar.tex
	dvipdf barbican.dvi ../pdf/projects/barbican.pdf
	dvipdf ceilometer.dvi ../pdf/projects/ceilometer.pdf
	dvipdf cinder.dvi ../pdf/projects/cinder.pdf
	dvipdf clients.dvi ../pdf/projects/clients.pdf
	dvipdf commonlibraries.dvi ../pdf/projects/commonlibraries.pdf
	dvipdf deployment.dvi ../pdf/projects/deployment.pdf
	dvipdf designate.dvi ../pdf/projects/designate.pdf
	dvipdf documentation.dvi ../pdf/projects/documentation.pdf
	dvipdf glance.dvi ../pdf/projects/glance.pdf
	dvipdf heat.dvi ../pdf/projects/heat.pdf
	dvipdf horizon.dvi ../pdf/projects/horizon.pdf
	dvipdf infrastructure.dvi ../pdf/projects/infrastructure.pdf
	dvipdf ironic.dvi ../pdf/projects/ironic.pdf
	dvipdf keystone.dvi ../pdf/projects/keystone.pdf
	dvipdf manila.dvi ../pdf/projects/manila.pdf
	dvipdf neutron.dvi ../pdf/projects/neutron.pdf
	dvipdf nova.dvi ../pdf/projects/nova.pdf
	dvipdf others.dvi ../pdf/projects/others.pdf
	dvipdf qualityassurance.dvi ../pdf/projects/qualityassurance.pdf
	dvipdf releasecyclemanagement.dvi ../pdf/projects/releasecyclemanagement.pdf
	dvipdf sahara.dvi ../pdf/projects/sahara.pdf
	dvipdf swift.dvi ../pdf/projects/swift.pdf
	dvipdf trove.dvi ../pdf/projects/trove.pdf
	dvipdf zaqar.dvi ../pdf/projects/zaqar.pdf
